BlueShopping/BlueShopping/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('logined/', include('logined.urls', namespace='logined')),
    path('account/', include('account.urls', namespace='account')),
    re_path('.*', views.main),
]

BlueShopping/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('cloth/', views.cloth, name='cloth'),
    path('cap/', views.cap, name='cap'),
    path('thing/', views.thing, name='thing'),
    path('pants/', views.pants, name='pants'),
    path('contact/', views.contact, name='contact'),
    path('mained',views.mained,name='mained'),
    path('logined',views.logined,name='logined'),
    path('register',views.register,name='register'),    
    path('logining',views.logining,name='logining'),
    
]

BlueShopping/main/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib import messages
from account.forms import UserForm
from django.contrib.auth import logout as auth_logout

def main(request):
    '''
    Render the main page
    '''
    return render(request, 'main/main.html',)
def cloth(request):
    '''
    Render the about page
    '''
    return render(request, 'main/cloth.html')
def cap(request):
    '''
    Render the about page
    '''
    return render(request, 'main/cap.html')
def pants(request):
    '''
    Render the about page
    '''
    return render(request, 'main/pants.html')
def thing(request):
    '''
    Render the about page
    '''
    return render(request, 'main/thing.html')
def contact(request):
    '''
    Render the about page
    '''
    return render(request, 'main/contact.html')
def mained(request):
    '''
    Render the mained page
    '''
    return render(request, 'mained/mained.html')
def clothed(request):
    '''
    Render the clothed page
    '''
    return render(request, 'mained/clothed.html')
def caped(request):
    '''
    Render the caped page
    '''
    return render(request, 'mained/caped.html')
def pantsed(request):
    '''
    Render the pantsed page
    '''
    return render(request, 'mained/pantsed.html')
def thinged(request):
    '''
    Render the thinged page
    '''
    return render(request, 'mained/thinged.html')
def contacted(request):
    '''
    Render the contact page
    '''
    return render(request, 'mained/contacted.html')
def register(request):
    '''
    Register a new user
    '''
    template = 'account/register.html'
    if request.method == 'GET':
        return render(request, template, {'userForm':UserForm()})

    # POST
    userForm = UserForm(request.POST)
    if not userForm.is_valid():
        return render(request, template, {'userForm':userForm})

    userForm.save()
    messages.success(request, '歡迎註冊')
    return redirect('mained:mained')
def add(request):
    '''
    Render the add page
    '''
    return render(request, 'mained/add.html')
def logined(request):
    '''
    Render the logined page
    '''
    return render(request, 'logined/logined.html')  
def logining(request):
    '''
    Login an existing user
    '''
    template = 'account/logining.html'
    if request.method == 'GET':
        return render(request, template)

    # POST
    username = request.POST.get('username')
    password = request.POST.get('password')
    if not username or not password:    # Server-side validation
        messages.error(request, '請填資料')
        return render(request, template)

    user = authenticate(username=username, password=password)
    if not user:    # authentication fails
        messages.error(request, '登入失敗')
        return render(request, template)

    # login success
    auth_login(request, user)
    messages.success(request, '登入成功')
    return redirect('mained:mained') 
def logout(request):
    '''
    Logout the user
    '''
    auth_logout(request)
    messages.success(request, '歡迎再度光臨')
    return redirect('main:main') 

BlueShopping/main/templates/main/base.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
{% block css %}{% endblock %}
</head>
<body>
{% include 'main/menu.html' %}
<h2>部落格 -- {% block heading %}{% endblock %}</h2>
{% include 'main/messages.html' %}
{% block content %}{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% block script %}{% endblock %}
</body>
</html>

BlueShopping/main/templates/main/cap.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
 <ul id="menu">
<li><a href="{% url 'main:main' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a></li>
  <li><a href="{% url 'account:logining' %}">登入</a></li>
  </ul>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'main:cloth' %}">衣服</a></li><br>
  	<li><a href="{% url 'main:pants' %}">褲子</a></li><br>
  	<li><a href="{% url 'main:cap' %}">帽子</a></li><br>
  	<li><a href="{% url 'main:thing' %}">其他</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'main:contact' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>帽子</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/main/templates/main/cloth.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
 <ul id="menu">
<li><a href="{% url 'main:main' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a></li>
  <li><a href="{% url 'account:logining' %}">登入</a></li>
  </ul>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'main:cloth' %}">衣服</a></li><br>
  	<li><a href="{% url 'main:pants' %}">褲子</a></li><br>
  	<li><a href="{% url 'main:cap' %}">帽子</a></li><br>
  	<li><a href="{% url 'main:thing' %}">其他</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'main:contact' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>衣服</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/main/templates/main/contact.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/contact.css' %}">
  </head>
  <body>
  <a href="{% url 'main:main' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a>
  <ul style="list-style-type:none">
      <li><a href="{% url 'account:logining' %}">登入</a></li> 
    </ul>
    <h3>聯絡我們</h3>
    <h3>電話：0800-9487946</h3>
    <h3>信箱：12345678@gmail.com</h3>
    <h3>地址：地球村天龍縣地龍市火龍路ABC號69之6號</h3>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
   <ul id="menu">
<a href="{% url 'main:main' %}">
<img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a>

  <li><a href="{% url 'account:logining' %}">登入</a></li>
  </ul>
  </div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
    <ul style="list-style-type:none">
    <li><a href="{% url 'main:cloth' %}">衣服</a></li><br>
    <li><a href="{% url 'main:pants' %}">褲子</a></li><br>
    <li><a href="{% url 'main:cap' %}">帽子</a></li><br>
    <li><a href="{% url 'main:thing' %}">其他</li><br>
    </ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'main:contact' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
   <h1>主頁</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/main/templates/main/pants.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
 <ul id="menu">
<li><a href="{% url 'main:main' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a></li>
  <li><a href="{% url 'account:logining' %}">登入</a></li>
  </ul>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'main:cloth' %}">衣服</a></li><br>
  	<li><a href="{% url 'main:pants' %}">褲子</a></li><br>
  	<li><a href="{% url 'main:cap' %}">帽子</a></li><br>
  	<li><a href="{% url 'main:thing' %}">其他</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'main:contact' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>褲子</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/main/templates/main/thing.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
 <ul id="menu">
<li><a href="{% url 'main:main' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a></li>
  <li><a href="{% url 'account:logining' %}">登入</a></li>
  </ul>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'main:cloth' %}">衣服</a></li><br>
  	<li><a href="{% url 'main:pants' %}">褲子</a></li><br>
  	<li><a href="{% url 'main:cap' %}">帽子</a></li><br>
  	<li><a href="{% url 'main:thing' %}">其他</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'main:contact' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>其他</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>