BlueShopping/BlueShopping/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('logined/', include('logined.urls', namespace='logined')),
    path('account/', include('account.urls', namespace='account')),
    re_path('.*', views.main),
]

BlueShopping/logined/urls.py
from django.urls import path
from main import views


app_name = 'mained'
urlpatterns = [
    path('', views.main, name='main'),
    path('clothed/', views.clothed, name='clothed'),
    path('caped/', views.caped, name='caped'),
    path('thinged/', views.thinged, name='thinged'),
    path('pantsed/', views.pantsed, name='pantsed'),
    path('contacted/', views.contacted, name='contacted'),
    path('mained',views.mained,name='mained'),
    path('add/',views.add,name='add'),
    
]

BlueShopping/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('cloth/', views.cloth, name='cloth'),
    path('cap/', views.cap, name='cap'),
    path('thing/', views.thing, name='thing'),
    path('pants/', views.pants, name='pants'),
    path('contact/', views.contact, name='contact'),
    path('mained',views.mained,name='mained'),
    path('logined',views.logined,name='logined'),
    path('register',views.register,name='register'),    
    path('logining',views.logining,name='logining'),
    
]

BlueShopping/logined/models.py
from django.db import models

# Create your models here.

BlueShopping/logined/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib import messages
from account.forms import UserForm
from django.contrib.auth import logout as auth_logout

def main(request):
    '''
    Render the main page
    '''
    return render(request, 'main/main.html',)
def cloth(request):
    '''
    Render the about page
    '''
    return render(request, 'main/cloth.html')
def cap(request):
    '''
    Render the about page
    '''
    return render(request, 'main/cap.html')
def pants(request):
    '''
    Render the about page
    '''
    return render(request, 'main/pants.html')
def thing(request):
    '''
    Render the about page
    '''
    return render(request, 'main/thing.html')
def contact(request):
    '''
    Render the about page
    '''
    return render(request, 'main/contact.html')
def clothed(request):
    '''
    Render the clothed page
    '''
    return render(request, 'mained/clothed.html')
def caped(request):
    '''
    Render the caped page
    '''
    return render(request, 'mained/caped.html')
def pantsed(request):
    '''
    Render the pantsed page
    '''
    return render(request, 'mained/pantsed.html')
def thinged(request):
    '''
    Render the thinged page
    '''
    return render(request, 'mained/thinged.html')
def contacted(request):
    '''
    Render the contact page
    '''
    return render(request, 'mained/contacted.html')
def mained(request):
    '''
    Render the mained page
    '''
    return render(request, 'mained/mained.html')
def add(request):
    '''
    Render the add page
    '''
    return render(request, 'mained/add.html')
def register(request):
    '''
    Register a new user
    '''
    template = 'accountr/register.html'
    if request.method == 'GET':
        return render(request, template, {'userForm':UserForm()})

    # POST
    userForm = UserForm(request.POST)
    if not userForm.is_valid():
        return render(request, template, {'userForm':userForm})

    userForm.save()
    messages.success(request, '歡迎註冊')
    return redirect('mained:mained')
def logining(request):
    '''
    Login an existing user
    '''
    template = 'account/logining.html'
    if request.method == 'GET':
        return render(request, template)

    # POST
    username = request.POST.get('username')
    password = request.POST.get('password')
    if not username or not password:    # Server-side validation
        messages.error(request, '請填資料')
        return render(request, template)

    user = authenticate(username=username, password=password)
    if not user:    # authentication fails
        messages.error(request, '登入失敗')
        return render(request, template)

    # login success
    auth_login(request, user)
    messages.success(request, '登入成功')
    return redirect('mained:mained')
def logout(request):
    '''
    Logout the user
    '''
    auth_logout(request)
    messages.success(request, '歡迎再度光臨')
    return redirect('main:main')

BlueShopping/logined/templates/mained/add.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
   <ul id="menu">
<a href="{% url 'mained:mained' %}">
<img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a>
  <li>會員帳號:({{ user.username }})</li>
  <li><a href="{% url 'main:main' %}">登出</a></li>
  </ul>
  </div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
    <ul style="list-style-type:none">
    <li><a href="{% url 'mained:mained' %}">新增商品</a></li><br>
    </ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'mained:contacted' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
  <h3><label for="good">商品名稱:</label></h3>
  <input type="text" name="good" value="" id="good"> <br />
  <h3><label for="kind">商品種類:</label></h3>
  <select name=kind>
  <option value=ture>衣服 </option>
  <option value=true>褲子</option>
  <option value=ture>帽子 </option>
  <option value=ture>其他 </option>
</select><br />
  <h3><label for="write">商品描述:</label></h3>
 <textarea rows=20 px cols=100 px name="write"></textarea>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/logined/templates/mained/caped.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
 <ul id="menu">
<li><a href="{% url 'mained:main' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a></li>
  <li>會員帳號:({{ user.username }})</li>
  <li><a href="{% url 'main:main' %}">登出</a></li>
  <li>
  </ul>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'mained:clothed' %}">衣服</a></li><br>
  	<li><a href="{% url 'mained:pantsed' %}">褲子</a></li><br>
  	<li><a href="{% url 'mained:caped' %}">帽子</a></li><br>
  	<li><a href="{% url 'mained:thinged' %}">其他</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'mained:contacted' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>帽子</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/logined/templates/mained/clothed.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
 <ul id="menu">
<li><a href="{% url 'mained:mained' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a></li>
  <li>會員帳號:({{ user.username }})</li>
  <li><a href="{% url 'main:main' %}">登出</a></li>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'mained:clothed' %}">衣服</a></li><br>
  	<li><a href="{% url 'mained:pantsed' %}">褲子</a></li><br>
  	<li><a href="{% url 'mained:caped' %}">帽子</a></li><br>
  	<li><a href="{% url 'mained:thinged' %}">其他</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'mained:contacted' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>衣服</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/logined/templates/mained/contacted.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/contact.css' %}">
  </head>
  <body>
  <a href="{% url 'mained:mained' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a>
  <li>會員帳號:({{ user.username }})</li>
  <li><a href="{% url 'main:main' %}">登出</a></li>
  

    <h3>聯絡我們</h3>
    <h3>電話：0800-9487946</h3>
    <h3>信箱：12345678@gmail.com</h3>
    <h3>地址：地球村天龍縣地龍市火龍路ABC號69之6號</h3>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/logined/templates/mained/mained.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
   <ul id="menu">
<a href="{% url 'mained:mained' %}">
<img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a>
  <li>會員帳號:({{ user.username }})</li>
  <li><a href="{% url 'main:main' %}">登出</a></li>
  </ul>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'mained:clothed' %}">衣服</a></li><br>
  	<li><a href="{% url 'mained:pantsed' %}">褲子</a></li><br>
  	<li><a href="{% url 'mained:caped' %}">帽子</a></li><br>
  	<li><a href="{% url 'mained:thinged' %}">其他</a></li><br>
    <li><a href="{% url 'mained:add' %}">新增商品</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'mained:contacted' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>主頁</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/logined/templates/mained/pantsed.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
 <ul id="menu">
<li><a href="{% url 'mained:mained' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a></li>
  <li>會員帳號:({{ user.username }})</li>
  <li><a href="{% url 'main:main' %}">登出</a></li>
  </ul>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'mained:clothed' %}">衣服</a></li><br>
  	<li><a href="{% url 'mained:pantsed' %}">褲子</a></li><br>
  	<li><a href="{% url 'mained:caped' %}">帽子</a></li><br>
  	<li><a href="{% url 'mained:thinged' %}">其他</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'mained:contacted' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>褲子</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>

BlueShopping/logined/templates/mained/thinged.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Blue Shopping</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  <nav>
  <div id="nav">
 <h1>
 <ul id="menu">
<li><a href="{% url 'mained:mained' %}">
  <img src="{% static 'main/img/logo1.png' %}" title="main" alt="BlueShopping" ></a></li>
  <li>會員帳號:({{ user.username }})</li>
  <li><a href="{% url 'main:main' %}">登出</a></li>
  </ul>
	</div></nav>
<header>
<div id="header">
  <h1><marquee direction="right" height="50" scrollamount="10" behavior="alternate">
  Nice to meet you！！！</marquee></h1></div></header>
  <br>
  <aside>
  <h1>
  <div id="aside">
  	<ul style="list-style-type:none">
  	<li><a href="{% url 'mained:clothed' %}">衣服</a></li><br>
  	<li><a href="{% url 'mained:pantsed' %}">褲子</a></li><br>
  	<li><a href="{% url 'mained:caped' %}">帽子</a></li><br>
  	<li><a href="{% url 'mained:thinged' %}">其他</li><br>
  	</ul>
  </h1></div>
  <div id="aside">
   <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><h1>
     <ul style="list-style-type:none">
     <li><a href="{% url 'mained:contacted' %}">聯絡我們</a></li></ul>
  </h1></div>
  </aside>
  <div id="content">
 	 <h1>其他</h1>
  </div>
  </div>
    <p>{{ like }}</p>
  </body>
</html>